config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  resources :cat_rental_requests, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  get 'cat_rental_requests/:id/approve', to: 'cat_rental_requests#approve'
  get 'cat_rental_requests/:id/deny', to: 'cat_rental_requests#deny' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = [
    "Black",
    "Grey",
    "White",
    "Orange",
    "Tabby"
  ]

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validate :sex_format
  validates_inclusion_of :color, :in => COLORS

  has_many :rental_requests,
    class_name: :CatRentalRequest,
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  
    def age
      obj_age = Date.today.year - birth_date.year 
      unless Date.today.month >= birth_date.month && Date.today.day >= birth_date.day
        obj_age -= 1
      end
      obj_age
    end

  def sex_format
    unless sex == 'M' || sex == "F"
      errors[:sex] << "must be 'M' or 'F'"
    end
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  STATUSES = [
    "PENDING",
    "APPROVED",
    "DENIED"
  ]

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates_inclusion_of :status, :in => STATUSES
  validate :does_not_overlap_approved_request

  belongs_to :cat,
    class_name: :Cat,
    foreign_key: :cat_id,
    primary_key: :id

  def does_not_overlap_approved_request
    overlapping_approved_requests.empty?
  end
  
  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def overlapping_requests
    fill_in_value = self.id ? self.id : 0

    CatRentalRequest.where('end_date >= ?', self.start_date)
      .where('start_date <= ?', self.end_date)
      .where('cat_id = ?', self.cat_id)
      .where.not('id = ?', fill_in_value)
  end

  def approve!
    CatRentalRequest.transaction do
      self.save unless self.id
      self.update_attribute(:status, "APPROVED")

      overlapping_pending_requests.each do |request|
        request.update_attribute(:status, "DENIED")
      end
    end
    true
  end

  def deny!
    if self.id 
        self.update_attribute(:status, "DENIED")
      else
        self.status = "DENIED"
        self.save
      end
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: "PENDING")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cats = Cat.all
    render :new
  end

  def create
    @request = CatRentalRequest.new(cat_rental_request_params)
    if @request.save
      redirect_to cat_url(@request)
    else
      render :new
    end
  end

  def approve
    request = CatRentalRequest.find_by_id(params[:id])
    request.approve!
    redirect_to cat_url(request.cat_id)
  end

  def deny
    request = CatRentalRequest.find_by_id(params[:id])
    request.deny!
    redirect_to cat_url(request.cat_id)
  end

  private

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all 
    render :index
  end

  def show
    @cat = Cat.find_by_id(params[:id])
    @current_rental_requests = CatRentalRequest
      .where(cat_id: params[:id])
      .where.not(status: "DENIED")
      .order(:start_date)
    
    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Create a rental request</h1>

<form action="<%= cat_rental_requests_url %>" method="post">

  <label for="cat">Select a cat:</label>
  <select name="cat_rental_request[cat_id]" id="cat">
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>%"><%= cat.name %></option>
    <% end %>
  </select>

  <br>
  <br>
  <label for="start_date">Start date:</label>
  <input type="date" name="cat_rental_request[start_date]" id="start_date">

  <br>
  <br>
  <label for="end_date">End date:</label>
  <input type="date" name="cat_rental_request[end_date]" id="end_date">

  <br>
  <br>
  <input type="submit" value="Create Request">

</form>

app/views/cats/_form.html.erb
<% if action == :edit && cat.persisted? %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit && cat.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name:</label>
  <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">
  
  <br><br>
  <label for="birth_date">Birth date:</label>
  <input type="date" id="birth_date" name="cat[birth_date]" value="<%= cat.birth_date if cat.birth_date %>">

  <br><br>
  <label>Sex:</label>
  <input type="radio" id="female" value="F" name="cat[sex]"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="female">F</label>
  <input type="radio" id="male" value="M" name="cat[sex]" 
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="male">M</label>

  <br><br>
  <label for="color">Color:</label>
  <select id="color" name="cat[color]">
    <option disabled selected="<%= "true" unless cat.color %>" >-- Select Color --</option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %>><%= color %></option>
    <% end %>
  </select>

  <br><br>
  <label for="description">Description:</label>
  <textarea name="cat[description]">
      <%= cat.description %>
  </textarea>

  <br><br>
  <input type="submit" value="<%= action == :edit ? "Update cat" : "Create cat" %>">

  <ul>
    <% @cat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</form>

app/views/cats/edit.html.erb
<h1>Edit cat!</h1>

<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
 
<div class="main">
  <div class="sub-header">
    <h2>all of the cats in the world</h2>
    <a href="#">Add cat<img src="" alt=""></a>
  </div>

  <ul>
    <% @cats.each do |cat| %>
     <li><%= link_to "#{cat.name}", cat_url(cat) %></li>
    <%end%>
  </ul>

app/views/cats/new.html.erb
<h1>Add a new cat!</h1>

<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

<br><br>
<h3>Rental Requests for <%= @cat.name %>:</h3>
<table>
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Status</th>
  </tr>
  <% @current_rental_requests.each do |request| %>
    <tr>
      <td><%= request.start_date %></td>
      <td><%= request.end_date %></td>
      <td><%= request.status %></td>
      <% if request.status == "PENDING" %>
      <td><form action="/cat_rental_requests/<%= request.id %>/approve" method="get">
        <input type="submit" value="Approve">
      </form></td>
      <td><form action="/cat_rental_requests/<%= request.id %>/deny" method="get">
        <input type="submit" value="Deny">
      </form></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValerieCampbell99Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-logo-wrapper"><a href="#" class="header-logo">99 Cats</a> </div>
      <div class="header-nav-wrapper">
        <ul class="header-nav">
          <li><a href="#">Sign in</a></li>
          <li><a href="#">Sign up</a></li>
        </ul>
      </div>
    </header>
    <%= yield %>
  </body>
</html>